#!/usr/bin/env bash
#Starts nginx as nginx user

chmod a+rwx /etc/nginx/nginx.conf
chown -R nginx /etc/nginx
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
