#!/usr/bin/env bash
# tests whether the file exists and is regular
if test -e "holbertonschool"
then
	echo "holbertonschool file exists"
	if test -s "holbertonschool" # file is empty
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if test -f "holbertonschool" # file is regular
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
