#!/usr/bin/env bash
#Check if a file exists 
FILE="holbertonschool"
wd=$PWD
pth="${wd}/${FILE}"
if [ -e "$pth" ]
then
	echo "${FILE} file exists"
	if [ -s "$pth" ] 
	then
		echo "${FILE} file is not empty"
	else
		echo "${FILE} file is empty"
	fi
	if [ -f "$pth" ]
	then	
		echo "${FILE} file is a regular file"
	fi
else
	echo "${FILE} file does not exist"
fi
